import {getStudio} from './studio-engine.js';
const STYLE_ID='utiterv-studio-style';
let inspector=location.search.includes('studio=1');
let interactionMode='edit';
let applying=false;
function cssProp(k){return k.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())}
function buildCss(data){
 const t=data.theme||{};let css=`:root{--studio-primary:${t.primary||'#007fff'};--studio-accent:${t.accent||'#14e8c9'};--studio-text:${t.text||'#050505'};--studio-surface:${t.surface||'#fff'};--blue:${t.primary||'#007fff'};--turq:${t.accent||'#14e8c9'};--ink:${t.text||'#050505'};--paper:${t.surface||'#fff'};}@keyframes studioFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-12px)}}@keyframes studioSpin{to{transform:rotate(360deg)}}@keyframes studioPulse{0%,100%{transform:scale(1)}50%{transform:scale(1.06)}}@keyframes studioFade{from{opacity:.55}to{opacity:1}}`;
 for(const [selector,styles] of Object.entries(data.styles||{})){css+=`\n${selector}{${Object.entries(styles).map(([k,v])=>`${cssProp(k)}:${v}!important`).join(';')}}`}
 const rs=data.responsiveStyles||{};const emit=(bucket)=>Object.entries(bucket||{}).map(([selector,styles])=>`${selector}{${Object.entries(styles).map(([k,v])=>`${cssProp(k)}:${v}!important`).join(';')}}`).join('\n');css+=`\n@media(max-width:599px){${emit(rs.mobile)}}\n@media(min-width:600px) and (max-width:899px){${emit(rs.tablet)}}\n@media(min-width:900px){${emit(rs.desktop)}}`;css+=`\n${data.customCss||''}`;return css;
}
function applyClasses(data){
 document.querySelectorAll('[data-studio-classes]').forEach(el=>{const selector=el.dataset.studioClassSelector;if(selector&&data.classes?.[selector])return;el.dataset.studioClasses.split(' ').filter(Boolean).forEach(c=>el.classList.remove(c));delete el.dataset.studioClasses;delete el.dataset.studioClassSelector});
 for(const [selector,value] of Object.entries(data.classes||{})){try{document.querySelectorAll(selector).forEach(el=>{const previous=(el.dataset.studioClasses||'').split(/\s+/).filter(Boolean);previous.forEach(c=>el.classList.remove(c));const cs=value.split(/\s+/).filter(Boolean);cs.forEach(c=>el.classList.add(c));el.dataset.studioClasses=cs.join(' ');el.dataset.studioClassSelector=selector})}catch{}}
}
function applyTexts(data){
 document.querySelectorAll('[data-studio-text-selector]').forEach(el=>{const selector=el.dataset.studioTextSelector;if(selector&&Object.prototype.hasOwnProperty.call(data.texts||{},selector))return;if(el.dataset.studioOriginalHtml!=null)el.innerHTML=el.dataset.studioOriginalHtml;delete el.dataset.studioOriginalHtml;delete el.dataset.studioTextSelector});
 for(const [selector,value] of Object.entries(data.texts||{})){let nodes=[];try{nodes=[...document.querySelectorAll(selector)]}catch{}nodes.forEach(el=>{if(el.dataset.studioOriginalHtml==null)el.dataset.studioOriginalHtml=el.innerHTML;el.dataset.studioTextSelector=selector;if(el.textContent!==String(value))el.textContent=value})}
}
function applyAssets(data){
 document.querySelectorAll('[data-studio-asset-selector]').forEach(el=>{const selector=el.dataset.studioAssetSelector;if(selector&&data.assets?.[selector])return;if(el.tagName==='IMG'&&el.dataset.studioOriginalSrc!=null)el.setAttribute('src',el.dataset.studioOriginalSrc);if(el.dataset.studioBg==='1'){el.style.removeProperty('background-image');el.style.removeProperty('background-size');el.style.removeProperty('background-position');el.style.removeProperty('background-repeat')}delete el.dataset.studioOriginalSrc;delete el.dataset.studioBg;delete el.dataset.studioAssetSelector});
 for(const [selector,a] of Object.entries(data.assets||{})){let nodes=[];try{nodes=[...document.querySelectorAll(selector)]}catch{}nodes.forEach(el=>{el.dataset.studioAssetSelector=selector;if(a.mode==='image'&&el.tagName==='IMG'){if(el.dataset.studioOriginalSrc==null)el.dataset.studioOriginalSrc=el.getAttribute('src')||'';if(el.getAttribute('src')!==a.src)el.setAttribute('src',a.src)}else{el.style.setProperty('background-image',`url("${a.src}")`,'important');el.style.setProperty('background-size',a.size||'contain','important');el.style.setProperty('background-position',a.position||'center','important');el.style.setProperty('background-repeat','no-repeat','important');el.dataset.studioBg='1'}})}
}
function applyInsertions(data){
 const wanted=new Set((data.insertions||[]).map(x=>x.id));
 document.querySelectorAll('[data-studio-insert-id]').forEach(el=>{if(!wanted.has(el.dataset.studioInsertId))el.remove()});
 for(const item of data.insertions||[]){
  if(document.querySelector(`[data-studio-insert-id="${CSS.escape(item.id)}"]`))continue;
  let target=null;try{target=document.querySelector(item.targetSelector)}catch{}if(!target)continue;
  let img;if(item.kind==='component'){const tag=item.tag||'div';img=document.createElement(tag);img.textContent=item.text||({heading:'Új címsor',text:'Új szöveges tartalom',button:'Új gomb',card:'Új kártya'}[item.componentType]||'Új elem');if(item.componentType==='button'){img.className='button'}else if(item.componentType==='card'){img.className='card';img.style.padding='20px'}else if(item.componentType==='spacer'){img.style.height='32px';img.setAttribute('aria-label','Térköz')} }else{img=document.createElement('img');img.src=item.src;img.alt=item.alt||item.name||'';img.className='studio-inserted-asset';img.style.maxWidth='100%';img.style.height='auto'}img.dataset.studioInsertId=item.id;
  if(item.position==='prepend')target.prepend(img);else if(item.position==='before')target.before(img);else if(item.position==='after')target.after(img);else target.append(img);
 }
}
function apply(){if(applying)return;applying=true;try{const d=getStudio();let style=document.getElementById(STYLE_ID);if(!style){style=document.createElement('style');style.id=STYLE_ID;document.head.append(style)}const css=buildCss(d);if(style.textContent!==css)style.textContent=css;applyInsertions(d);applyClasses(d);applyTexts(d);applyAssets(d)}finally{queueMicrotask(()=>{applying=false})}}
function selectorFor(el){if(el.dataset?.studioInsertId)return `[data-studio-insert-id="${CSS.escape(el.dataset.studioInsertId)}"]`;if(el.id)return `#${CSS.escape(el.id)}`;const path=[];let n=el;while(n&&n!==document.body&&path.length<5){let s=n.tagName.toLowerCase();const useful=[...n.classList].filter(c=>!c.startsWith('is-')&&!c.startsWith('studio-')).slice(0,2);if(useful.length)s+='.'+useful.map(CSS.escape).join('.');else{const same=[...n.parentElement.children].filter(x=>x.tagName===n.tagName);if(same.length>1)s+=`:nth-of-type(${same.indexOf(n)+1})`}path.unshift(s);n=n.parentElement}return path.join(' > ')}
function label(el){return (el.getAttribute('aria-label')||el.getAttribute('alt')||el.textContent||el.tagName).trim().replace(/\s+/g,' ').slice(0,55)}
function sendTree(){if(!inspector||window.parent===window)return;const nodes=[...document.querySelectorAll('#app header, #view > *, #view section, #view article, #view button, #view img, #view h1, #view h2, #view h3, #view p')].slice(0,260).map(el=>({selector:selectorFor(el),tag:el.tagName.toLowerCase(),label:label(el),text:el.textContent?.trim()||'',depth:Math.min(5,selectorFor(el).split(' > ').length-1)}));window.parent.postMessage({type:'utiterv-studio-tree',nodes},'*')}

function select(el){if(interactionMode!=='edit')return;document.querySelectorAll('.studio-selected').forEach(x=>x.classList.remove('studio-selected'));el.classList.add('studio-selected');const r=el.getBoundingClientRect();window.parent.postMessage({type:'utiterv-studio-select',selector:selectorFor(el),tag:el.tagName.toLowerCase(),label:label(el),text:el.textContent?.trim()||'',rect:{width:Math.round(r.width),height:Math.round(r.height)}},'*')}
if(inspector){const s=document.createElement('style');s.id='studio-inspector-style';s.textContent='.studio-selected{outline:2px solid #14e8c9!important;outline-offset:3px!important}.studio-hover{outline:1px dashed #14e8c9!important;outline-offset:2px!important;cursor:pointer!important}';document.head.append(s);document.addEventListener('mouseover',e=>{if(interactionMode!=='edit'||e.target.closest('#splash'))return;document.querySelectorAll('.studio-hover').forEach(x=>x.classList.remove('studio-hover'));e.target.classList.add('studio-hover')},true);document.addEventListener('mouseout',e=>e.target.classList.remove('studio-hover'),true);document.addEventListener('click',e=>{if(interactionMode!=='edit'||e.target.closest('[data-studio-ui]'))return;const el=e.target.closest('img,button,a,h1,h2,h3,p,article,section,div,span');if(!el)return;setTimeout(()=>{if(el.isConnected)select(el)},0)})}
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();window.parent.postMessage({type:'utiterv-studio-shortcut',key:e.key.toLowerCase(),shift:e.shiftKey},'*')}},true);
window.addEventListener('message',e=>{if(e.data?.type==='utiterv-studio-mode'){interactionMode=e.data.mode==='test'?'test':'edit';document.documentElement.dataset.studioMode=interactionMode;document.querySelectorAll('.studio-selected,.studio-hover').forEach(x=>x.classList.remove('studio-selected','studio-hover'));const st=document.getElementById('studio-inspector-style');if(st)st.disabled=interactionMode!=='edit';if(interactionMode==='edit')sendTree();}if(e.data?.type==='utiterv-studio-refresh'){apply();sendTree()}if(e.data?.type==='utiterv-studio-focus'){try{const el=document.querySelector(e.data.selector);if(el){el.scrollIntoView({behavior:'smooth',block:'center'});select(el)}}catch{}}});
window.addEventListener('storage',apply);window.addEventListener('utiterv-studio-changed',apply);
new MutationObserver(()=>{if(applying)return;apply();clearTimeout(window.__studioTreeTimer);window.__studioTreeTimer=setTimeout(sendTree,300)}).observe(document.documentElement,{childList:true,subtree:true});
apply();setTimeout(sendTree,700);
