'use strict';
var VERSION='pagescms-content-platform-6.1';
var STATIC_CACHE='utiterv-static-'+VERSION;
var RUNTIME_CACHE='utiterv-runtime-'+VERSION;
var APP_SHELL='/index.html',OFFLINE_URL='/offline.html';
var APP_FILES=['/','/index.html','/offline.html','/manifest.webmanifest','/css/app.css','/css/foundation.css','/css/pwa.css','/css/theme.css','/css/color-system.css','/js/app.js','/js/pwa.js','/js/theme.js','/js/site-shell.js','/js/content-engine.js','/js/project-content.js','/js/cms-blocks.js','/js/content-navigation.js','/js/onmagam.js','/js/helyzeteim.js','/js/kapcsolataim.js','/js/bonus.js','/content/project.json','/content/errors.json','/content/home.json','/content/ui.json','/content/offline.json','/content/assets.json','/content/custom/topics.json','/content/shared/competencies.json','/content/shared/onmagam-data.json','/content/modules/galaxy-guide/index.json','/content/modules/galaxy-guide/materials.json','/content/modules/galaxy-guide/videos.json','/content/modules/quick-win/index.json','/content/modules/quick-win/cv.json','/content/modules/quick-win/firstday.json','/content/modules/quick-win/interview.json','/content/modules/quick-win/jobhunt.json','/content/modules/quick-win/legal.json','/content/modules/quick-win/linkedin.json','/content/modules/quick-win/redflags.json','/content/modules/quick-win/scenarios.json','/content/modules/quick-win/world.json','/content/modules/quit-go/index.json','/content/modules/quit-go/breathing.json','/content/modules/quit-go/careers.json','/content/modules/quit-go/marketfacts.json','/content/modules/quit-go/mindfulness.json','/content/modules/quit-go/preboarding.json','/content/modules/quit-go/quiz.json','/content/modules/quit-go/survival.json','/content/modules/win-win/index.json','/content/modules/win-win/communication.json','/content/modules/win-win/digital.json','/content/modules/win-win/generations.json','/content/modules/win-win/glossary.json','/content/modules/win-win/phrases.json','/content/modules/win-win/twosides.json','/content/modules/galaxy-guide/dynamic-pages.json','/content/modules/quick-win/dynamic-pages.json','/content/modules/quit-go/dynamic-pages.json','/content/modules/win-win/dynamic-pages.json','/assets/SVG_ASSETS/LOGO/LOGO_PINPOINT_CON.svg','/assets/SVG_ASSETS/LOGO/LOGO_TIPO.svg'];
function collectStrings(value,out){if(typeof value==='string'&&/^(assets|audio|video|downloads)\//.test(value))out.add('/'+value);else if(typeof value==='string'&&/^\/(assets|audio|video|downloads)\//.test(value))out.add(value);else if(Array.isArray(value))value.forEach(function(v){collectStrings(v,out)});else if(value&&typeof value==='object')Object.values(value).forEach(function(v){collectStrings(v,out)})}
async function mediaFiles(){var out=new Set();await Promise.all(APP_FILES.filter(function(url){return /\.json$/.test(url)}).map(async function(url){try{var r=await fetch(url,{cache:'reload'});if(!r.ok)return;collectStrings(await r.json(),out)}catch(e){}}));return Array.from(out)}
async function cacheOne(cache,url){try{var r=await fetch(url,{cache:'reload'});if(r.ok)await cache.put(url,r.clone())}catch(e){}}
self.addEventListener('install',function(event){event.waitUntil((async function(){var cache=await caches.open(STATIC_CACHE),media=await mediaFiles();await Promise.all(APP_FILES.concat(media).map(function(url){return cacheOne(cache,url)}));await self.skipWaiting()})())});
self.addEventListener('activate',function(event){event.waitUntil(caches.keys().then(function(keys){return Promise.all(keys.map(function(key){return key.indexOf('utiterv-')===0&&key!==STATIC_CACHE&&key!==RUNTIME_CACHE?caches.delete(key):Promise.resolve(false)}))}).then(function(){return self.clients.claim()}))});
self.addEventListener('message',function(event){if(event.data&&event.data.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('fetch',function(event){var request=event.request;if(request.method!=='GET')return;var url;try{url=new URL(request.url)}catch(e){return}if(url.origin!==self.location.origin)return;if(request.mode==='navigate'){event.respondWith(fetch(request).then(function(response){if(response&&response.ok){var copy=response.clone();caches.open(RUNTIME_CACHE).then(function(c){c.put(request,copy)});}return response}).catch(function(){return caches.match(APP_SHELL,{ignoreSearch:true}).then(function(c){return c||caches.match(OFFLINE_URL,{ignoreSearch:true})})}));return}event.respondWith(fetch(request).then(function(response){if(response&&response.ok){var copy=response.clone();caches.open(RUNTIME_CACHE).then(function(c){c.put(request,copy)});}return response}).catch(function(){return caches.match(request,{ignoreSearch:true})}))});
